# Generated by Django 4.2 on 2023-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hours_of_paid_courses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hours_of_taken_courses',
            field=models.IntegerField(null=True),
        ),
    ]
