# Generated by Django 4.2 on 2023-04-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_hours_of_paid_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_hours',
            field=models.IntegerField(null=True),
        ),
    ]
