# Generated by Django 4.2 on 2023-04-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_course_course_date_remove_course_course_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HoursUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_hours', models.IntegerField(null=True)),
                ('used_hours', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Admin'), (4, 'Secretary')], default=1, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.agency')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_date_hour_of_appointment',
            new_name='course_appointment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_instructor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='related_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.quiz'),
        ),
        migrations.AddField(
            model_name='hoursuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.user'),
        ),
        migrations.AddField(
            model_name='agency',
            name='courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='agency_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.agency'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_attending_user',
            field=models.ManyToManyField(to='app.user'),
        ),
    ]
