# Generated by Django 4.2 on 2023-04-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agency_hoursuser_question_quiz_user_delete_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='course_attending_instructor',
            field=models.ForeignKey(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor+', to='app.user'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_attending_user',
        ),
        migrations.AddField(
            model_name='course',
            name='course_attending_user',
            field=models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student+', to='app.user'),
        ),
    ]
