# Generated by Django 4.2 on 2023-04-16 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_course_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Student'), ('2', 'Instructor'), ('3', 'Admin'), ('4', 'Secretary')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='taken_course_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, related_name='users', to='app.course'),
        ),
    ]
