# Generated by Django 4.2 on 2023-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_paid_course_hours_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Admin'), (4, 'Secretary')], null=True),
        ),
    ]
