# Generated by Django 4.1.7 on 2023-04-18 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_students',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
