# Generated by Django 4.1.7 on 2023-04-18 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_assigned_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_students',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_students',
            field=models.ManyToManyField(limit_choices_to={'role': 1}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
