# Generated by Django 4.1.7 on 2023-04-19 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_assigned_students_user_assigned_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 1}, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
