# Generated by Django 4.1.7 on 2023-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_course_instructor_course_assigned_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_students',
        ),
    ]
