# Generated by Django 4.1.7 on 2023-04-23 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_student_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.AddField(
            model_name='course',
            name='selected_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_schedule', to=settings.AUTH_USER_MODEL, to_field='student_timeslots'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_timeslots',
        ),
        migrations.AddField(
            model_name='user',
            name='student_timeslots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_timeslots', to='app.timeslot', unique=True),
        ),
    ]
