# Generated by Django 4.1.7 on 2023-04-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_course_date_remove_course_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='selected_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
