# Generated by Django 4.1.7 on 2023-04-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_course_selected_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='selected_schedule',
        ),
    ]
