# Generated by Django 4.2 on 2023-05-07 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_assigned_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_instructor',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_student',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 1)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
